### ISSUE TITLE
Missing a boolean literal

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#28]
As far as I could tell, there is no special parsing for `true` and `false`. They just parse as identifiers.

**Comment by alaviss** [comment]
I didn't include boolean grammars because of what you said: they are not special and are treated as identifiers.

The only use case I could think of for `true`/`false` nodes is so that they can be highlighted easily using a language query by editors. I think that could already be done using string pattern matchers that most editors already supports, weakening the case of adding another tree-sitter-only grammar quirk.

**Comment by aMOPel** [comment]
> because of what you said

whoops :D
