### ISSUE TITLE
elif, else, except and finally create strange call structure

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#41]
### Current Behavior

```nim
let a = 5
finally                  # <- same for else, elif, except (`of` parses as prefix operator)
```

```scheme
let_section [0, 0] - [1, 7]
  "let" [0, 0] - [0, 3]
  variable_declaration [0, 4] - [1, 7]
    symbol_declaration_list [0, 4] - [0, 5]
      symbol_declaration [0, 4] - [0, 5]
        name: identifier [0, 4] - [0, 5]
    value: "=" [0, 6] - [0, 7]
    value: call [0, 8] - [1, 7]                                    # <- weird
      function: integer_literal [0, 8] - [0, 9]       
      argument_list [1, 0] - [1, 7]                    
        identifier [1, 0] - [1, 7]                               
```

### Expected Behavior

```nim
let a = 5
if
```
```scheme
let_section [0, 0] - [0, 9]
  "let" [0, 0] - [0, 3]
  variable_declaration [0, 4] - [0, 9]
    symbol_declaration_list [0, 4] - [0, 5]
      symbol_declaration [0, 4] - [0, 5]
        name: identifier [0, 4] - [0, 5]
    value: "=" [0, 6] - [0, 7]
    value: integer_literal [0, 8] - [0, 9]
ERROR [1, 0] - [2, 0]
  "if" [1, 0] - [1, 2]
```
or
```nim
let a = 5
asdf
```
```scheme
let_section [0, 0] - [0, 9]
  "let" [0, 0] - [0, 3]
  variable_declaration [0, 4] - [0, 9]
    symbol_declaration_list [0, 4] - [0, 5]
      symbol_declaration [0, 4] - [0, 5]
        name: identifier [0, 4] - [0, 5]
    value: "=" [0, 6] - [0, 7]
    value: integer_literal [0, 8] - [0, 9]
identifier [1, 0] - [1, 4]
```

**Comment by alaviss** [comment]
Yea this is a known bug with those keywords.

They have some special scanner sauce that always applies to not emit a layout terminator (ie. a semicolon). The parser used to be able to cope with this by externalizing the tokens, but it made many states unmergable and ballooned the parser size.

I can try again now that the parser size is lowered.

**Comment by aMOPel** [comment]
Is it related to this: https://nim-lang.org/docs/manual.html#macros-postminusstatement-blocks ?

**Comment by alaviss** [comment]
Yea.

It's hard to get away with putting those keywords in the scanner because they interfere with state merging. You can imagine what happens when Nim's syntax allows for those to appear in basically everything.

There might be a trick to handling this using tagged layout (ie. tags with what could be in them) so it's certainly an avenue for research.

**Comment by aMOPel** [comment]
Can you copy the technique the Nim parser is using to do it?

**Comment by aMOPel** [comment]
> You can imagine what happens when Nim's syntax allows for those to appear in basically everything.

I was wondering anyways, if you want to try to narrow down certain options in expressions, eg object constructors only allow for `:` while array construction only allows for `=` etc.

Also I was wondering about the keyword() function you're using to make keywords case insensitive. Only many keywords aren't case insensitive to that extent or at all (can't remember rn).

**Comment by alaviss** [comment]
In terms of copying the indentation handling verbatim, it's simply not possible. `tree-sitter` was not designed for annotated tokens (which is how Nim does its indentation). I can mimic it somewhat using the annotated tokens approach, which as explained above, is terrible for parser size and presumably performance.

> I was wondering anyways, if you want to try to narrow down certain options in expressions, eg object constructors only allow for `:` while array construction only allows for `=` etc.

This is already done to somewhat the same extent as the Nim parser. Paradoxically, the more constraints you add, the more the parser inflates. This is because it could no longer merge very similar parsing branches. It is a known weakness of LR-style parser as far as my understanding of them goes due to the approach of statically handling all possible parse interpretations.

> Also I was wondering about the keyword() function you're using to make keywords case insensitive. Only many keywords aren't case insensitive to that extent or at all (can't remember rn).

We can fix that if you find any of those. According to the manual and my read of the Nim lexer, all keywords are subjected to style insensitivity, which makes sense because it makes writing the lexer a lot simpler.

**Comment by aMOPel** [comment]
> We can fix that if you find any of those. According to the manual and my read of the Nim lexer, all keywords are subjected to style insensitivity, which makes sense because it makes writing the lexer a lot simpler.

I see. I guess the thing I noticed with the case insensitive keywords, was just that the first letter has to be lower case, but you seem to have that covered in `keyword_regex()`.

If that feature has a noticeable impact on parser size/performance I think it could be dropped.
