### ISSUE TITLE
`else_branch` doesn't have `condition:` field, which is inconsistent

### ISSUE THREAD

**Issue by aMOPel** [alaviss/tree-sitter-nim#67]
Same goes for `of_branch`. And while you're at it, `except_branch` and `finally_branch` could also have `consequence:` fields.

Also I noticed that `_if_body` repeats the `alternative:` field. Didn't you say it's bad to repeat fields?
But if you wanna keep it, `_case_body` and `_try_tail` should also have those repeating fields for consistency.

**Comment by alaviss** [comment]
> `else_branch` doesn't have `condition` field.

Of course it won't have that field since there is no condition.

> Same goes for `of_branch`. And while you're at it, `except_branch` and `finally_branch` could also have consequence: fields.

Ah you meant `consequence`. We can add that, definitely. I think I was tip-toeing between `consequence` and `body` and ended up not using either of them.

`finally` will definitely uses `body` though, it's always reached and is not a "consequence" of any action.

> Didn't you say it's bad to repeat fields?

It's about expectation, an `if` will likely to have more than one `alternative`, so I figured it'd be fine to repeat the field, as done by many other grammars.

> But if you wanna keep it, `_case_body` and `_try_tail` should also have those repeating fields for consistency.

It's just there aren't any good "field name" that I could think of for them :P, feel free to leave your suggestions here.

**Comment by aMOPel** [comment]
I feel like `(case)` can definitely have `alternative:` fields. Yes technically they are not alternatives to the discriminator line, but all the branches are alternatives to each other.

**Comment by aMOPel** [comment]
I looked into the python parser and it has

- `body:` for (else_branch)
- `body:` for (case) (containing all branches)
- `alternative:` for branches in (case)
- `consequence:` for (of_branch)
- `body:` for (try)
- nothing for (except_branch) and (finally_branch), but it really should use `body:` there too
- couldn't find field names for (except_branch) and (finally_branch)
